package VistaUsuario;

/**
 *
 * @author Group1
 */
public class Inicio extends javax.swing.JFrame {

        public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_principal = new javax.swing.JPanel();
        Porcentaje = new javax.swing.JLabel();
        Titulo_principal = new javax.swing.JLabel();
        Icono_OCD = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        Lema = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Panel_principal.setBackground(new java.awt.Color(252, 195, 91));

        Porcentaje.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Porcentaje.setForeground(new java.awt.Color(255, 255, 255));
        Porcentaje.setText("%");
        Porcentaje.setName("Percent"); // NOI18N

        Titulo_principal.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        Titulo_principal.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_principal.setText("BIENVENIDO A ORGANIZE-CLEAR-DATA");

        Icono_OCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/istockphoto-1393629140-612x612 (3).png"))); // NOI18N

        ProgressBar.setForeground(new java.awt.Color(204, 204, 204));

        Lema.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        Lema.setForeground(new java.awt.Color(255, 255, 255));
        Lema.setText("LA MEJOR OPCION PARA TU NEGOCIO");

        javax.swing.GroupLayout Panel_principalLayout = new javax.swing.GroupLayout(Panel_principal);
        Panel_principal.setLayout(Panel_principalLayout);
        Panel_principalLayout.setHorizontalGroup(
            Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_principalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titulo_principal)
                .addGap(57, 57, 57))
            .addGroup(Panel_principalLayout.createSequentialGroup()
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(Icono_OCD))
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(Porcentaje))
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(Lema)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        Panel_principalLayout.setVerticalGroup(
            Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_principalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Titulo_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(Icono_OCD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lema, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(Porcentaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Inicio Mysplash = new Inicio();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        //Starting the main function
        java.awt.EventQueue.invokeLater(() -> {
            Mysplash.setVisible(true);
        });

        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(20);
                Mysplash.ProgressBar.setValue(i);
                Mysplash.Porcentaje.setText(Integer.toString(i) + "%");
            }
        } catch (InterruptedException e) {

        }
        new Login().setVisible(true);

        Mysplash.dispose(); //To distroy/Clean JFrame window
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icono_OCD;
    private javax.swing.JLabel Lema;
    private javax.swing.JPanel Panel_principal;
    private javax.swing.JLabel Porcentaje;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel Titulo_principal;
    // End of variables declaration//GEN-END:variables
}
